### ISSUE TITLE
Properly test on other platforms than Raspbian

### ISSUE THREAD

**Issue by koenvervloesem** [koenvervloesem/snipskit#4]
I took great pains to create SnipsKit as platform-agnostic as possible, e.g. for the search paths of the [configuration and assistant files](https://github.com/koenvervloesem/snipskit/blob/master/src/snipskit/config.py). However, currently SnipsKit is only fully tested on Raspbian.

While the code is continuously [tested](https://github.com/koenvervloesem/snipskit/tree/master/tests) on [Travis CI](https://travis-ci.com/koenvervloesem/snipskit) on a virtual Ubuntu Xenial Xerus (16.04 LTS) system, it's not put to the test in a real Ubuntu system with Snips installed.

It's also not tested on other platforms that should be supported, like macOS and other ARM systems than the Raspberry Pi.

It would be helpful if someone could run the test suite in a virtual Python environment on one of these platforms and tell me the result, positive or negative:

    python3 -m venv venv
    . venv/bin/activate
    pip install -r requirements/install/all.txt
    pip install -r requirements/development.txt
    ./scripts/run_tests.sh

But even more, it would be really helpful if someone could run an [example app](https://github.com/koenvervloesem/snipskit/blob/master/examples/hermes_listen_for_intent.py) or, even better, a real app using SnipsKit (such as [Keep quiet](https://github.com/koenvervloesem/snips-app-keep-quiet) or [Assistant information](https://github.com/koenvervloesem/snips-app-assistant-information)) on one of these platforms, and tell me the result, positive or negative.

**Comment by oziee** [comment]
run on macOS 

```
================================================= test session starts =================================================
platform darwin -- Python 3.7.2, pytest-4.4.0, py-1.8.0, pluggy-0.9.0 -- /Users/optiplex/snipskit/venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/optiplex/snipskit, inifile: pytest.ini
plugins: mock-1.10.3, cov-2.6.1, pyfakefs-3.5.8
collected 62 items                                                                                                    

tests/test_services_integration.py::test_version_output SKIPPED                                                 [  1%]
tests/test_services_integration.py::test_is_installed SKIPPED                                                   [  3%]
tests/test_services_integration.py::test_is_running SKIPPED                                                     [  4%]
tests/test_services_integration.py::test_model_version SKIPPED                                                  [  6%]
tests/test_services_integration.py::test_installed SKIPPED                                                      [  8%]
tests/test_services_integration.py::test_running SKIPPED                                                        [  9%]
tests/test_services_integration.py::test_versions SKIPPED                                                       [ 11%]
tests/test_services_integration.py::test_version SKIPPED                                                        [ 12%]
tests/test_tools.py::test_find_path[file_system0-files0-None] PASSED                                            [ 14%]
tests/test_tools.py::test_find_path[file_system1-files1-None] PASSED                                            [ 16%]
tests/test_tools.py::test_find_path[file_system2-files2-None] PASSED                                            [ 17%]
tests/test_tools.py::test_find_path[file_system3-files3-None] PASSED                                            [ 19%]
tests/test_tools.py::test_find_path[file_system4-files4-/etc/snips.toml] PASSED                                 [ 20%]
tests/test_tools.py::test_find_path[file_system5-files5-/etc/snips.toml] PASSED                                 [ 22%]
tests/test_tools.py::test_find_path[file_system6-files6-None] PASSED                                            [ 24%]
tests/test_tools.py::test_find_path[file_system7-files7-None] PASSED                                            [ 25%]
tests/test_tools.py::test_find_path[file_system8-files8-/usr/local/etc/snips.toml] PASSED                       [ 27%]
tests/test_tools.py::test_find_path[file_system9-files9-None] PASSED                                            [ 29%]
tests/test_tools.py::test_find_path[file_system10-files10-/etc/snips.toml] PASSED                               [ 30%]
tests/test_tools.py::test_find_path[file_system11-files11-/etc/snips.toml] PASSED                               [ 32%]
tests/config/test_config_app.py::test_app_config_default PASSED                                                 [ 33%]
tests/config/test_config_app.py::test_app_config_path PASSED                                                    [ 35%]
tests/config/test_config_app.py::test_app_config_write PASSED                                                   [ 37%]
tests/config/test_config_app.py::test_app_config_write_with_filename PASSED                                     [ 38%]
tests/config/test_config_assistant.py::test_assistant_config_default PASSED                                     [ 40%]
tests/config/test_config_assistant.py::test_assistant_config_with_filename PASSED                               [ 41%]
tests/config/test_config_assistant.py::test_assistant_config_key_not_found PASSED                               [ 43%]
tests/config/test_config_assistant.py::test_assistant_config_broken_json PASSED                                 [ 45%]
tests/config/test_config_assistant.py::test_assistant_config_file_not_found PASSED                              [ 46%]
tests/config/test_config_assistant.py::test_assistant_config_no_config_file PASSED                              [ 48%]
tests/config/test_config_snips.py::test_snips_config_default PASSED                                             [ 50%]
tests/config/test_config_snips.py::test_snips_config_with_filename PASSED                                       [ 51%]
tests/config/test_config_snips.py::test_snips_config_key_not_found PASSED                                       [ 53%]
tests/config/test_config_snips.py::test_snips_config_broken_toml PASSED                                         [ 54%]
tests/config/test_config_snips.py::test_snips_config_file_not_found PASSED                                      [ 56%]
tests/config/test_config_snips.py::test_snips_config_no_config_file PASSED                                      [ 58%]
tests/config/test_config_snips_mqtt.py::test_snips_config_mqtt_default PASSED                                   [ 59%]
tests/config/test_config_snips_mqtt.py::test_snips_config_mqtt_hostname PASSED                                  [ 61%]
tests/config/test_config_snips_mqtt.py::test_snips_config_mqtt_hostname_authentication PASSED                   [ 62%]
tests/config/test_config_snips_mqtt.py::test_snips_config_mqtt_tls PASSED                                       [ 64%]
tests/hermes/test_apps_hermes.py::test_snips_app_hermes_default PASSED                                          [ 66%]
tests/hermes/test_apps_hermes.py::test_snips_app_hermes_default_with_assistant_path PASSED                      [ 67%]
tests/hermes/test_apps_hermes.py::test_snips_app_hermes_snips_config PASSED                                     [ 69%]
tests/hermes/test_apps_hermes.py::test_snips_app_hermes_config PASSED                                           [ 70%]
tests/hermes/test_components_hermes_connection.py::test_snips_component_hermes_connection_default PASSED        [ 72%]
tests/hermes/test_components_hermes_connection.py::test_snips_component_hermes_with_snips_config PASSED         [ 74%]
tests/hermes/test_components_hermes_connection.py::test_snips_component_hermes_connection_with_authentication PASSED [ 75%]
tests/hermes/test_components_hermes_connection.py::test_snips_component_hermes_connection_with_tls_and_authentication PASSED [ 77%]
tests/hermes/test_components_hermes_decorators.py::test_snips_component_hermes_decorators PASSED                [ 79%]
tests/mqtt/test_apps_mqtt.py::test_snips_app_mqtt_default PASSED                                                [ 80%]
tests/mqtt/test_apps_mqtt.py::test_snips_app_mqtt_default_with_assistant_path PASSED                            [ 82%]
tests/mqtt/test_apps_mqtt.py::test_snips_app_mqtt_snips_config PASSED                                           [ 83%]
tests/mqtt/test_apps_mqtt.py::test_snips_app_mqtt_config PASSED                                                 [ 85%]
tests/mqtt/test_components_mqtt_connection.py::test_snips_component_mqtt_connection_default PASSED              [ 87%]
tests/mqtt/test_components_mqtt_connection.py::test_snips_component_mqtt_with_snips_config PASSED               [ 88%]
tests/mqtt/test_components_mqtt_connection.py::test_snips_component_mqtt_connection_with_authentication PASSED  [ 90%]
tests/mqtt/test_components_mqtt_connection.py::test_snips_component_mqtt_connection_with_tls_and_authentication PASSED [ 91%]
tests/mqtt/test_components_mqtt_decorators.py::test_snips_component_mqtt_decorators PASSED                      [ 93%]
tests/mqtt/test_components_mqtt_pubsub_integration.py::test_snips_component_mqtt_pubsub SKIPPED                 [ 95%]
tests/mqtt/test_dialogue.py::test_dialogue_continue_session PASSED                                              [ 96%]
tests/mqtt/test_dialogue.py::test_dialogue_end_session PASSED                                                   [ 98%]
tests/mqtt/test_dialogue.py::test_dialogue_end_session_with_empty_text PASSED                                   [100%]

---------- coverage: platform darwin, python 3.7.2-final-0 -----------
Name                                Stmts   Miss  Cover
-------------------------------------------------------
src/conftest.py                         0      0   100%
src/snipskit/__init__.py                0      0   100%
src/snipskit/apps.py                   14      0   100%
src/snipskit/components.py             13      0   100%
src/snipskit/config.py                 69      0   100%
src/snipskit/exceptions.py              3      0   100%
src/snipskit/hermes/__init__.py         0      0   100%
src/snipskit/hermes/apps.py             6      0   100%
src/snipskit/hermes/components.py      20      0   100%
src/snipskit/hermes/decorators.py      21      0   100%
src/snipskit/mqtt/__init__.py           0      0   100%
src/snipskit/mqtt/apps.py               6      0   100%
src/snipskit/mqtt/components.py        29      0   100%
src/snipskit/mqtt/decorators.py        11      4    64%
src/snipskit/mqtt/dialogue.py           9      0   100%
src/snipskit/services.py               38     25    34%
src/snipskit/tools.py                   7      0   100%
-------------------------------------------------------
TOTAL                                 246     29    88%


======================================== 53 passed, 9 skipped in 4.53 seconds =========================================
```

**Comment by oziee** [comment]
I installed the `Assistant Information` app and there are errors

```
[15:50:42.345031] INFO :snips_skill_server_lib::runner: [assistant-information][err] Traceback (most recent call last):
[15:50:42.345075] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "./action-assistant-information.py", line 17, in <module>
[15:50:42.345246] INFO :snips_skill_server_lib::runner: [assistant-information][err]     i18n = importlib.import_module('translations.' + AssistantConfig()['language'])
[15:50:42.345269] INFO :snips_skill_server_lib::runner: [assistant-information][err]   File "/usr/local/var/snips/skills/koan.Assistant_information/venv/lib/python3.7/site-packages/snipskit/config.py", line 130, in __init__
[15:50:42.345958] INFO :snips_skill_server_lib::runner: [assistant-information][err]     raise AssistantConfigNotFoundError()
[15:50:42.346000] INFO :snips_skill_server_lib::runner: [assistant-information][err] snipskit.exceptions.AssistantConfigNotFoundError
[15:50:42.354392] WARN :snips_skill_server_lib::handler::nosandbox: child assistant-information has stopped with status `exit code: 1`
[15:50:42.354436] INFO :snips_skill_server_lib::runner            : restarting action assistant-information (restart_fails: 0)
[15:50:42.442043] INFO :snips_skill_server_lib::runner            : [assistant-information][err] Traceback (most recent call last):
[15:50:42.442076] INFO :snips_skill_server_lib::runner            : [assistant-information][err]   File "./action-assistant-information.py", line 17, in <module>
[15:50:42.442195] INFO :snips_skill_server_lib::runner            : [assistant-information][err]     i18n = importlib.import_module('translations.' + AssistantConfig()['language'])

```

**Comment by koenvervloesem** [comment]
Thanks for reporting this and for the detailed explanation! I just released version 0.5.3 where I added '/usr/local/etc/assistant' as a default assistant path that is searched for.

I'm also updating my apps to this version as a requirement so they can be run on a system with an assistant in that path. You can already try Assistant information, which I just updated. On Raspbian, there's an error now when setting up the virtual environment about the psutil wheel because I introduced that dependency in SnipsKit 0.5.3, but that's just a warning, I'll have to delve into that later...

**Comment by oziee** [comment]
i thought of that.. but the path i picked is not the same as what someone else would:)
i could have picked abc/xyz.. what ever it is i still need to put it into the snips.toml file
the two paths you had were correct.. it doesn't need '/usr/local/etc/assistant'

what is needs is a way for `AssistantConfig` to load the snipsconfig to be able to check if the snips.toml has a path set that is not the standard snips path (which you already were checking)

**Comment by koenvervloesem** [comment]
Oh I see, I thought it was the default path with brew.

But what you ask is done in the library. Thanks to your report, I see now that the logic in my apps is wrong. I need to do use the AssistantConfig object in the app class itself (then it works because it reads the assistant location from the Snips config), instead of outside the class, at the top of the module, as I'm doing now.

I'll have to rewrite the apps :-)

**Comment by koenvervloesem** [comment]
Ok, it's fixed now in Assistant information, going to fix the other apps too.

Thanks again for reporting this!

**Comment by koenvervloesem** [comment]
By the way, what's the default path for the assistant in macOS with brew? I thought it would be `/usr/local/share/snips/assistant/assistant.json` and put that in the search path of my code. Is that correct?

**Comment by koenvervloesem** [comment]
For future reference, and for when you need this in your own code: `AssistantConfig` just reads its configuration from a file. When you initialize a `SnipsApp`, it reads the location of the assistant from `snips.toml` and initializes an `AssistantConfig` object with the correct path. However, when you want to initialize an `AssistantConfig` object outside a `SnipsApp` object, such as is the case for reading the assistant's language in the Assistant information app you tried, you need to use `SnipsAppMixin().assistant` to get an `AssistantConfig` object initialized with the correct path. I'll add this to the documentation.

**Comment by oziee** [comment]
> By the way, what's the default path for the assistant in macOS with brew? I thought it would be `/usr/local/share/snips/assistant/assistant.json` and put that in the search path of my code. Is that correct?

yes that would be the default one

**Comment by oziee** [comment]
> For future reference, and for when you need this in your own code: `AssistantConfig` just reads its configuration from a file. When you initialize a `SnipsApp`, it reads the location of the assistant from `snips.toml` and initializes an `AssistantConfig` object with the correct path. However, when you want to initialize an `AssistantConfig` object outside a `SnipsApp` object, such as is the case for reading the assistant's language in the Assistant information app you tried, you need to use `SnipsAppMixin().assistant` to get an `AssistantConfig` object initialized with the correct path. I'll add this to the documentation.

so there will be an update to this app to fix that error?

**Comment by koenvervloesem** [comment]
> so there will be an update to this app to fix that error?

Yes it's fixed now.

**Comment by oziee** [comment]
this is where snips really shits me
i just updated the skill app

if i run your app manually either using python or bash it works fine
i have snips-skill-server running.. it is loading your app.. there are no error.. and yet when i say the same sentence as when i ran the code manually i get 
```
[20:30:06] [Nlu] detected intent koan:SnipsVersion with confidence score 0.596 for input "what snips version"
[20:30:06] [Dialogue] New intent detected koan:SnipsVersion with confidence 0.596
[20:30:11] [Dialogue] session with id 'c94f73f6-a91a-45a6-b52b-452823f1dc72' was ended on site zero. The session was ended because one of the component didn't respond in a timely manner
```

**Comment by oziee** [comment]
ahh... but wait.. the snips-skill-server.log file has some info as to the problem

```
INFO:snips_skill_server_lib::runner: [assistant-information][err] Traceback (most recent call last):
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "_ctypes/callbacks.c", line 232, in 'calling callback function'
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "/usr/local/var/snips/skills/koan.Assistant_information/venv/lib/python3.7/site-packages/hermes_python/ffi/wrappers.py", line 61, in convert_arguments_when_invoking_function
INFO:snips_skill_server_lib::runner: [assistant-information][err]     return func(hermes_client, *parsed_args)
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "./action-assistant-information.py", line 122, in handle_snips_version
INFO:snips_skill_server_lib::runner: [assistant-information][err]     version_string = check_output(SNIPS_VERSION_COMMAND).decode('utf-8')
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
INFO:snips_skill_server_lib::runner: [assistant-information][err]     **kwargs).stdout
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
INFO:snips_skill_server_lib::runner: [assistant-information][err]     with Popen(*popenargs, **kwargs) as process:
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
INFO:snips_skill_server_lib::runner: [assistant-information][err]     restore_signals, start_new_session)
INFO:snips_skill_server_lib::runner: [assistant-information][err]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
INFO:snips_skill_server_lib::runner: [assistant-information][err]     raise child_exception_type(errno_num, err_msg, err_filename)
INFO:snips_skill_server_lib::runner: [assistant-information][err] FileNotFoundError: [Errno 2] No such file or directory: 'snips-skill-server': 'snips-skill-server'
```

**Comment by koenvervloesem** [comment]
Is `snips-skill-server` in your path?

**Comment by oziee** [comment]
must be
```
(venv) server:koan.Assistant_information optiplex$ snips-skill-server --version
snips-skill-server 1.1.2 (0.62.3)
```

**Comment by koenvervloesem** [comment]
So this works when you run the app manually not not when run by the snips-skill-server? Is snips-skill-server running the apps is some kind of isolated container?

**Comment by oziee** [comment]
just a plain ol brew snips install.. nothing fancy

**Comment by oziee** [comment]
```(venv) server:koan.Assistant_information optiplex$ python
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import check_output
>>> version_string = check_output(['snips-skill-server', '--version']).decode('utf-8')
>>> print(version_string)
snips-skill-server 1.1.2 (0.62.3)
```

**Comment by oziee** [comment]
got it..
i have the snips services started with SUDO.. if they are started without SUDO it works:)

**Comment by koenvervloesem** [comment]
Cool that you got it solved. I was thinking through all possible scenarios and out of options :-)
